name: Cleanup Demo
description: Cleanup old demo files
inputs:
    AWS_ROLE:
        description: The AWS role name to assume using OIDC. This role should have the necesary privileges to deploy the website.
    AWS_REGION:
        description: The AWS region in which to deploy the website.
    AWS_BUCKET:
        description: The AWS S3 bucket in which to deploy the website.
runs:
    using: composite
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
          with:
              role-to-assume: ${{ inputs.AWS_ROLE }}
              aws-region: ${{ inputs.AWS_REGION }}
        - name: Clean demo files
          shell: bash
          run: bash ./.github/actions/cleanup-demo/cleanup-demo.sh ${{ github.head_ref || github.ref_name }} ${{ inputs.AWS_BUCKET }}
