name: Setup
description: Install Node, PNPM, and dependencies using cache
runs:
    using: composite
    steps:
        - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
          with:
              registry-url: 'https://registry.npmjs.org'
              node-version: 24
        - name: Enable corepack
          shell: bash
          run: corepack enable
        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          run: |
              echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
        - uses: actions/cache@v5
          name: Setup pnpm cache
          # inspired from https://github.com/pnpm/action-setup/tree/master#use-cache-to-reduce-installation-time
          with:
              path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-store-
        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
        - name: Setup turbo cache
          uses: actions/cache@v5
          with:
              path: node_modules/.cache/turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: |
                  turbo-${{ github.job }}-${{ github.ref_name }}-
