name: Setup
description: Install Node, PNPM, and dependencies using cache
runs:
    using: composite
    steps:
        - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
          with:
              registry-url: 'https://registry.npmjs.org'
        - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
          with:
              version: 8
              run_install: false
        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          run: |
              echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
        - uses: actions/cache@v3
          name: Setup pnpm cache
          # inspired from https://github.com/pnpm/action-setup/tree/master#use-cache-to-reduce-installation-time
          with:
              path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-store-
        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
        - name: Setup turbo cache
          uses: actions/cache@v3
          with:
              path: node_modules/.cache/turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: |
                  turbo-${{ github.job }}-${{ github.ref_name }}-
