name: 'Setup'
description: 'Install Node, PNPM, and dependencies using cache'
inputs:
    use_cache:
        default: 'true'
        description: Whether github actions cache should be used
    use_deployment_pipeline:
        default: 'false'
        description: Whether the deployment pipeline should be installed
runs:
    using: composite
    steps:
        - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        - uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd
          with:
              version: 7
              run_install: false
        - if: inputs.use_deployment_pipeline == 'true'
          uses: actions/setup-python@v3
        - if: inputs.use_deployment_pipeline == 'true'
          uses: coveo/deployment-pipeline-actions/setup@main
        - name: Get pnpm store directory
          id: pnpm-cache
          if: inputs.use_cache == 'true'
          shell: bash
          run: |
              echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
        - uses: actions/cache@v3
          name: Setup pnpm cache
          if: inputs.use_cache == 'true'
          # inspired from https://github.com/pnpm/action-setup/tree/master#use-cache-to-reduce-installation-time
          with:
              path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-store-
        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
        - name: Setup turbo cache
          if: inputs.use_cache == 'true'
          uses: actions/cache@v3
          with:
              path: node_modules/.cache/turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: |
                  turbo-${{ github.job }}-${{ github.ref_name }}-
