name: Snyk PNPM
description: Scan a pnpm repository using Snyk
inputs:
    pnpmLockInputPath:
        description: Relative path to the pnpm-lock.yaml file of the pnpm project you want to scan from the root
        required: true
        default: './pnpm-lock.yaml'
    SNYK_TOKEN:
        description: 'The Snyk Token'
        required: true
runs:
    using: 'composite'
    steps:
        - name: Prepare snyk folder
          shell: bash
          run: |
              mkdir -p snyk
              cp ${{ inputs.pnpmLockInputPath }} snyk
              rsync -arv --exclude action.yml ./.github/actions/snyk-pnpm/ ./snyk/
        - name: Convert pnpm lockfile to npm
          shell: bash
          working-directory: ./snyk
          run: |
              npm install
              mkdir -p scan-me
              npm run start pnpm-lock.yaml ./scan-me
        - name: Snyk
          shell: bash
          env:
              SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
          run: |
            npx --yes snyk test --org=coveo-admin-ui --severity-threshold=high --file=./snyk/scan-me/package-lock.json --sarif-file-output=./sarifs/snyk-test.sarif
            npx --yes snyk monitor --org=coveo-admin-ui --file=./snyk/scan-me/package-lock.json
        - name: Snyk Code
          shell: bash
          continue-on-error: true
          env:
              SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
          run: npx snyk code test --org=coveo-admin-ui --file=./snyk/scan-me/package-lock.json --sarif-file-output=./sarifs/snyk-code.sarif
        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@f0e3dfb30302f8a0881bb509b044e0de4f6ef589 # v2
          with:
              sarif_file: ./sarifs
        - name: Cleanup
          shell: bash
          run: rm -rf snyk
