name: 'Snyk PNPM'
description: 'Scan a pnpm repository using Snyk'
inputs:
    pnpmLockInputPath:
        description: 'Relative path to the pnpm-lock.yaml file of the pnpm project you want to scan from the root'
        required: true
        default: './pnpm-lock.yaml'
    SNYK_TOKEN:
        description: 'The Snyk Token'
        required: true
runs:
    using: 'composite'
    steps:
        - name: Prepare snyk folder
          shell: bash
          run: |
              mkdir -p snyk
              cp ${{ inputs.pnpmLockInputPath }} snyk
              rsync -arv --exclude action.yml ./.github/actions/snyk-pnpm/ ./snyk/
        - name: Convert pnpm lockfile to npm
          shell: bash
          working-directory: ./snyk
          run: |
              npm install
              mkdir -p scan-me
              npm run start pnpm-lock.yaml ./scan-me
        - name: Snyk Test
          env:
              SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
          shell: bash
          run: npx --yes snyk test --org=coveo-admin-ui --file=./snyk/scan-me/package-lock.json --strict-out-of-sync=false --json > snyk-result.json || true
        - name: Snyk Monitor
          env:
              SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
          shell: bash
          run: npx --yes snyk monitor --org=coveo-admin-ui --file=./snyk/scan-me/package-lock.json --strict-out-of-sync=false --json > snyk-monitor-result.json || true
        - name: Cleanup
          shell: bash
          run: rm -rf snyk
