name: Deploy
description: Deploy the website
inputs:
    AWS_ROLE:
        description: The AWS role name to assume using OIDC. This role should have the necesary privileges to deploy the website.
    AWS_REGION:
        description: The AWS region in which to deploy the website.
    AWS_BUCKET:
        description: The AWS S3 bucket in which to deploy the website.
outputs:
    demo-output-path:
        description: 'Path to the directory where the website was deployed'
        value: ${{ steps.s3-push.outputs.demo-output-path }}
runs:
    using: composite
    steps:
        - name: Compute base URL
          id: base-url
          uses: ./.github/actions/compute-base-url
          with:
              branch: ${{ github.head_ref || github.ref_name }}
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
          with:
              role-to-assume: ${{ inputs.AWS_ROLE }}
              aws-region: ${{ inputs.AWS_REGION }}
        - name: Push distribution code to s3 demo folder
          id: s3-push
          shell: bash
          env:
              BUCKET: ${{ inputs.AWS_BUCKET }}
              PLASMA_BASE_URL: ${{ steps.base-url.outputs.base-url }}
          run: bash ./.github/actions/deploy/deploy.sh "$BUCKET"
