// Don't edit this file, it gets overwriten on each build
import {ComponentMetadata} from '../ComponentsList';
export const BlankSlateMetadata: ComponentMetadata[] = [
    {
        name: 'additionalSection',
        description: 'Additionnal child to add to the blank slate',
        type: 'ReactNode',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'buttonClasses',
        description: 'Additional css classes the buttons should have',
        type: 'string[]',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'buttons',
        description: 'Array of buttons to add to the blank slate',
        type: 'IBaseActionOptions[]',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'classes',
        description: 'Additional css classes that the blank slate should have',
        type: 'string[]',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'containerClasses',
        description: 'Additional css classes the container should have',
        type: 'string[]',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'description',
        description: 'Description template to add to the blank slate',
        type: 'ReactNode',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'descriptionClassName',
        description: 'Additional css classes the description should have',
        type: 'string',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'icon',
        description: 'An icon to display above the title',
        type: 'Icon',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'title',
        description: 'Title of the blank slate',
        type: 'ReactNode',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'withModal',
        description: 'Whether the blank slate should have the css style to fit a modal',
        type: 'boolean',
        optional: true,
        defaultValue: 'false',
        deprecation: null,
        params: [],
    },
];
