// Don't edit this file, it gets overwriten on each build
import {ComponentMetadata} from '../ComponentsList';
export const ToastMetadata: ComponentMetadata[] = [
    {
        name: 'animate',
        description: 'Whether the toast has an animation upon entry',
        type: 'boolean',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'children',
        description: '',
        type: 'ReactNode',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'className',
        description: 'Additional css classes that the toast should have',
        type: 'string',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'dismiss',
        description: 'Timeout in ms after which the toast should disappear by itself',
        type: 'number',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'id',
        description: 'Unique identifier of the toast. Usefull to retrieve a specific toast in the redux state.',
        type: 'string',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'onClose',
        description: 'Callback function that will run after the toast is dismissed',
        type: '() => void',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'title',
        description: 'The content of the toast',
        type: 'ReactNode',
        optional: true,
        defaultValue: null,
        deprecation: null,
        params: [],
    },
    {
        name: 'type',
        description: 'The type of the toast',
        type: '"success" | "warning" | "error" | "info" | "download"',
        optional: true,
        defaultValue: '"success"',
        deprecation: null,
        params: [],
    },
    {
        name: 'content',
        description: '',
        type: 'ReactNode',
        optional: true,
        defaultValue: null,
        deprecation: 'Use children instead',
        params: [],
    },
    {
        name: 'dismissible',
        description: '',
        type: 'boolean',
        optional: true,
        defaultValue: null,
        deprecation: 'Toast are always dismissible by the user - will have no effect',
        params: [],
    },
    {
        name: 'isSmall',
        description: '',
        type: 'boolean',
        optional: true,
        defaultValue: null,
        deprecation: 'Do not use - will have no effect',
        params: [],
    },
    {
        name: 'onDestroy',
        description: '',
        type: '() => void',
        optional: true,
        defaultValue: null,
        deprecation: 'Use onClose instead',
        params: [],
    },
    {
        name: 'onRender',
        description: '',
        type: '() => void',
        optional: true,
        defaultValue: null,
        deprecation: '',
        params: [],
    },
];
