import * as Redux from 'redux';

import {IActionOptions} from './components/actions/Action.js';
import {IActionBarState} from './components/actions/ActionBarReducers.js';
import {IItemFilterState} from './components/actions/filters/ItemFilterReducers.js';
import {IAutocompleteState} from './components/autocomplete/AutocompleteReducers.js';
import {ICheckboxState} from './components/checkbox/CheckboxReducers.js';
import {IGroupableCheckboxesState} from './components/checkbox/GroupableCheckboxConstants.js';
import {CollapsibleState} from './components/collapsible/CollapsibleReducers.js';
import {IDatePickerState} from './components/datePicker/DatePickerReducers.js';
import {IDropState} from './components/drop/redux/DropReducers.js';
import {IDropdownState} from './components/dropdown/DropdownReducers.js';
import {IDropdownOption} from './components/dropdownSearch/DropdownSearch.js';
import {IDropdownSearchState} from './components/dropdownSearch/DropdownSearchReducers.js';
import {CodeEditorsState} from './components/editor/CodeEditorReducers.js';
import {JSONEditorState} from './components/editor/JSONEditorReducers.js';
import {IFacet} from './components/facets/Facet.js';
import {IFacetState} from './components/facets/FacetReducers.js';
import {FilepickerState} from './components/filepicker/FilepickerReducers.js';
import {IFilterState} from './components/filterBox/FilterBoxReducers.js';
import {IFlatSelectState} from './components/flatSelect/FlatSelectReducers.js';
import {IFlippableState} from './components/flippable/FlippableReducers.js';
import {IInlinePromptOptions} from './components/inlinePrompt/InlinePrompt.js';
import {IPromptState} from './components/inlinePrompt/InlinePromptReducers.js';
import {IInputState} from './components/input/InputReducers.js';
import {ILastUpdatedState} from './components/lastUpdated/LastUpdatedReducers.js';
import {IListBoxState} from './components/listBox/ListBoxReducers.js';
import {ILoadingState} from './components/loading/LoadingReducers.js';
import {IMenusState} from './components/menu/MenuReducers.js';
import {IModalState} from './components/modal/ModalReducers.js';
import {IPaginationState} from './components/navigation/pagination/NavigationPaginationReducers.js';
import {IPerPageState} from './components/navigation/perPage/NavigationPerPageReducers.js';
import {INumericInputsState} from './components/numericInput/NumericInputReducers.js';
import {IOptionPickerState} from './components/optionPicker/OptionPickerReducers.js';
import {IOptionsCycleState} from './components/optionsCycle/OptionsCycleReducers.js';
import {IPopoverState} from './components/popover/Popover.js';
import {IRadioSelectState} from './components/radio/RadioSelectReducers.js';
import {IRefreshCallbackReducerState} from './components/refresh/RefreshCallbackReducer.js';
import {ISearchBarState} from './components/searchBar/SearchBarReducers.js';
import {ISelectWithFilterCompositeState} from './components/select/hoc/SelectWithFilterReducers.js';
import {ISelectState} from './components/select/SelectReducers.js';
import {ISlidersState} from './components/slider/SliderReducers.js';
import {ISubNavigationState} from './components/subNavigation/SubNavigationReducers.js';
import {ITabGroupState} from './components/tab/TabReducers.js';
import {HOCTableState} from './components/table-hoc/reducers/TableHOCReducers.js';
import {HOCTableRowState} from './components/table-hoc/reducers/TableRowReducers.js';
import {ITableWithPaginationState} from './components/table-hoc/reducers/TableWithPaginationReducers.js';
import {ITableWithSortState} from './components/table-hoc/reducers/TableWithSortReducers.js';
import {ITablePredicate} from './components/tables/Table.js';
import {ITableStateModifier} from './components/tables/TableActions.js';
import {ITableHeaderCellsState} from './components/tables/TableHeaderCellReducers.js';
import {ITableData, ITablesState} from './components/tables/TableReducers.js';
import {ITableRowState} from './components/tables/TableRowReducers.js';
import {ITextAreaState} from './components/textarea/TextAreaReducers.js';
import {IToastsState} from './components/toast/ToastReducers.js';
import {ValidationsState} from './components/validation/ValidationState.js';
import {IStringListCompositeState} from './reusableState/customList/StringListReducers.js';
import {ComponentId} from './utils/ComponentUtils.js';

export interface PlasmaState {
    actionBars?: IActionBarState[];
    autocompletes?: IAutocompleteState[];
    checkboxes?: ICheckboxState[];
    collapsibles?: CollapsibleState[];
    datePickers?: IDatePickerState[];
    drop?: IDropState;
    dirtyComponents?: ComponentId[];
    dropdowns?: IDropdownState[];
    dropdownSearch?: IDropdownSearchState[];
    facets?: IFacetState[];
    filepickers?: FilepickerState;
    filters?: IFilterState[];
    flatSelect?: IFlatSelectState[];
    flippables?: IFlippableState[];
    groupableCheckboxes?: IGroupableCheckboxesState[];
    inputs?: IInputState[];
    itemFilters?: IItemFilterState[];
    codeEditors?: CodeEditorsState;
    jsonEditors?: JSONEditorState[];
    lastAction?: Redux.Action;
    lastUpdatedComposite?: ILastUpdatedState[];
    loadings?: ILoadingState[];
    listBoxes?: IListBoxState[];
    menus?: IMenusState;
    modals?: IModalState[];
    multilineIds?: IStringListCompositeState;
    numericInputs?: INumericInputsState;
    openModals?: string[];
    optionPickers?: IOptionPickerState[];
    optionsCycles?: IOptionsCycleState[];
    paginationComposite?: IPaginationState[];
    perPageComposite?: IPerPageState[];
    popovers?: IPopoverState[];
    prompts?: IPromptState[];
    radioSelects?: IRadioSelectState[];
    refreshCallback?: IRefreshCallbackReducerState;
    rows?: ITableRowState[];
    searchBars?: ISearchBarState[];
    selects?: ISelectState[];
    selectWithFilter?: ISelectWithFilterCompositeState;
    sliders?: ISlidersState;
    stringList?: IStringListCompositeState;
    subNavigations?: ISubNavigationState[];
    tabs?: ITabGroupState[];
    toastContainers?: IToastsState[];
    tableHeaderCells?: ITableHeaderCellsState;
    tables?: ITablesState;
    tableHOCHeader?: ITableWithSortState[];
    tableHOCPagination?: ITableWithPaginationState[];
    tableHOCRow?: HOCTableRowState[];
    tablesHOC?: HOCTableState[];
    textAreas?: ITextAreaState[];
    validation?: ValidationsState;
}

export interface IReduxActionsPayload {
    actions?: IActionOptions[];
    addedSelectedOption?: IDropdownOption;
    attributeToFormat?: string;
    attributeToSort?: string;
    calendarId?: string;
    color?: string;
    currentOption?: number;
    date?: Date;
    disabled?: boolean;
    disabledValues?: string[];
    expanded?: boolean;
    facet?: string;
    facetRow?: IFacet;
    filterText?: string;
    id?: string;
    ids?: string[];
    initialPerPage?: number;
    initialTableData?: ITableData;
    isCollapsible?: boolean;
    isDirty?: boolean;
    isInError?: boolean;
    isOpen?: boolean;
    isRange?: boolean;
    isSelected?: boolean;
    item?: string;
    label?: string;
    limit?: string;
    options?: IInlinePromptOptions;
    pageNb?: number;
    perPage?: number;
    predicates?: ITablePredicate[];
    searching?: boolean;
    selected?: string;
    shouldResetPage?: boolean;
    tableId?: string;
    tableStateModifier?: ITableStateModifier;
    totalEntries?: number;
    totalPages?: number;
    valid?: boolean;
    value?: string;
    yPosition?: number;
}
