import {Accordion} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Accordion,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A51291',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "description": figma.boolean('Description'),
            // "badge": figma.boolean('Badge'),
            // "infotoken": figma.boolean('Infotoken'),
            // "state": figma.enum('State', {
            //   "Default": "default",
            //   "Hover": "hover"
            // }),
            // "side": figma.enum('Side', {
            //   "Right": "right",
            //   "Left": "left"
            // }),
            // "open": figma.boolean('Open'),
            // "style": figma.enum('Style', {
            //   "Default": "default",
            //   "Contained": "contained",
            //   "Nested": "nested"
            // })
        },
        example: (props) => <Accordion />,
    },
);
