import {ActionIcon} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    ActionIcon,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A49884',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "iconSwap": figma.instance('Icon Swap'),
            // "variant": figma.enum('Variant', {
            //   "Primary": "primary",
            //   "Secondary": "secondary",
            //   "Tertiary": "tertiary",
            //   "Quaternary": "quaternary"
            // }),
            // "state": figma.enum('State', {
            //   "Default": "default",
            //   "Hover": "hover",
            //   "Disabled": "disabled"
            // })
        },
        example: (props) => <ActionIcon />,
    },
);
