import {Alert, Anchor, Text} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Alert.Information,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Information'},
        props: {
            message: figma.textContent('Message'),
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Information',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link, message}) => (
            <Alert.Information withCloseButton={withCloseButton} title={title}>
                <Text>{message}</Text>
                {link}
            </Alert.Information>
        ),
    },
);

figma.connect(
    Alert.Advice,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Advice'},
        props: {
            message: figma.textContent('Message'),
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Advice',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link, message}) => (
            <Alert.Advice withCloseButton={withCloseButton} title={title}>
                <Text>{message}</Text>
                {link}
            </Alert.Advice>
        ),
    },
);

figma.connect(
    Alert.Warning,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Warning'},
        props: {
            message: figma.textContent('Message'),
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Warning!',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link, message}) => (
            <Alert.Warning withCloseButton={withCloseButton} title={title}>
                <Text>{message}</Text>
                {link}
            </Alert.Warning>
        ),
    },
);

figma.connect(
    Alert.Critical,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Caution'},
        props: {
            message: figma.textContent('Message'),
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Bummer!',
            }),
            button2: figma.boolean('Button 2', {
                true: figma.instance('*'),
            }),
            button: figma.boolean('Button', {
                true: figma.instance('*'),
            }),
            link: figma.boolean('Link'),
        },
        example: ({withCloseButton, title, link, button2, button, message}) => (
            <Alert.Critical withCloseButton={withCloseButton} title={title}>
                <Text>{message}</Text>
                {link}
                {button2}
                {button}
            </Alert.Critical>
        ),
    },
);
