import {Alert, Anchor} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Alert,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Information'},
        props: {
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Information',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link}) => (
            <Alert withCloseButton={withCloseButton} title={title}>
                {link}
            </Alert>
        ),
    },
);

figma.connect(
    Alert,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Advice'},
        props: {
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Advice',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link}) => (
            <Alert withCloseButton={withCloseButton} title={title}>
                {link}
            </Alert>
        ),
    },
);

figma.connect(
    Alert,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Warning'},
        props: {
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Warning!',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link}) => (
            <Alert withCloseButton={withCloseButton} title={title}>
                {link}
            </Alert>
        ),
    },
);

figma.connect(
    Alert,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50375',
    {
        variant: {Variant: 'Caution'},
        props: {
            withCloseButton: figma.boolean('Show Close'),
            title: figma.boolean('Show Title', {
                true: 'Bummer!',
            }),
            // "button2": figma.boolean('Button 2'),
            // "button": figma.boolean('Button'),
            link: figma.boolean('Link', {
                true: (
                    <Anchor href="https://coveord.com" target="_blank">
                        Learn more
                    </Anchor>
                ),
            }),
        },
        example: ({withCloseButton, title, link}) => (
            <Alert withCloseButton={withCloseButton} title={title}>
                {link}
            </Alert>
        ),
    },
);
