import {Badge} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Badge,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50600',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "iconLeft": figma.boolean('Icon Left'),
            // "iconRight": figma.boolean('Icon Right'),
            // "swapLeft": figma.instance('Swap Left'),
            // "swapRight": figma.instance('Swap Right'),
            // "placeholder": figma.string('Placeholder'),
            // "type": figma.enum('Type', {
            //   "Primary": "primary",
            //   "Secondary": "secondary",
            //   "Warning": "warning",
            //   "Critical": "critical",
            //   "Disabled": "disabled"
            // }),
            // "size": figma.enum('Size', {
            //   "Small": "small",
            //   "Large": "large"
            // })
        },
        example: (props) => <Badge />,
    },
);
