import {BrowserPreview} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    BrowserPreview,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A52207',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "pagination": figma.boolean('Pagination'),
            // "infotoken": figma.boolean('Infotoken'),
            // "input": figma.boolean('Input'),
            // "segmentedControl": figma.boolean('Segmented Control'),
            // "variant": figma.enum('Variant', {
            //   "Swap content": "swap-content",
            //   "Empty State": "empty-state"
            // })
        },
        example: (props) => <BrowserPreview />,
    },
);
