import {Button} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Button,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A49794',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "swapLeft": figma.instance('Swap Left'),
            // "swapRight": figma.instance('Swap Right'),
            // "leftIcon": figma.boolean('Left Icon'),
            // "rightIcon": figma.boolean('Right Icon'),
            // "placeholder": figma.string('Placeholder'),
            // "variant": figma.enum('Variant', {
            //   "Primary": "primary",
            //   "Secondary": "secondary",
            //   "Tertiary": "tertiary",
            //   "Quaternary": "quaternary"
            // }),
            // "state": figma.enum('State', {
            //   "Default": "default",
            //   "Hover": "hover",
            //   "Disabled": "disabled"
            // })
        },
        example: (props) => <Button />,
    },
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Button,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A49737',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "swapLeft": figma.instance('Swap Left'),
            // "swapRight": figma.instance('Swap Right'),
            // "leftIcon": figma.boolean('Left Icon'),
            // "rightIcon": figma.boolean('Right Icon'),
            // "placeholder": figma.string('Placeholder'),
            // "variant": figma.enum('Variant', {
            //   "Primary": "primary",
            //   "Secondary": "secondary",
            //   "Tertiary": "tertiary",
            //   "Quaternary": "quaternary"
            // }),
            // "state": figma.enum('State', {
            //   "Default": "default",
            //   "Hover": "hover",
            //   "Disabled": "disabled"
            // })
        },
        example: (props) => <Button />,
    },
);
