import {Button} from '@coveord/plasma-mantine';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Button,
    'https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Pretine-7-for-Coveo?node-id=6332-3933&m=dev',
    {
        props: {
            rightIcon: figma.boolean('Right Icon', {
                true: figma.children('*'),
            }),
            leftIcon: figma.boolean('Left Icon', {
                true: figma.children('*'),
            }),
            placeholder: figma.string('Placeholder'),
            variant: figma.enum('Variant', {
                Filled: 'filled',
                Default: 'default',
                White: 'white',
                Light: 'light',
                Outline: 'outline',
                Subtle: 'subtle',
            }),
            color: figma.enum('Color', {
                Blue: 'blue',
                Yellow: 'yellow',
                Red: 'red',
                Green: 'green',
                Gray: 'gray',
            }),
            size: figma.enum('Size', {
                md: 'md',
                xl: 'xl',
                lg: 'lg',
                sm: 'sm',
                xs: 'xs',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Disabled: 'disabled',
                Hover: 'hover',
            }),
        },
        example: ({variant, size, color, placeholder, leftIcon, rightIcon}) => (
            <Button variant={variant} size={size} color={color} leftSection={leftIcon} rightSection={rightIcon}>
                {placeholder}
            </Button>
        ),
    },
);
