import {Checkbox} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    Checkbox,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma-3.0---Components?node-id=7-50069&m=dev',
    {
        props: {
            indeterminate: figma.enum('Checked', {
                Indeterminate: true,
            }),
            label: figma.boolean<string, never>('Show Label', {
                true: figma.textContent('Text here'),
            }),
            disabled: figma.enum('State', {
                Disabled: true,
            }),
            readOnly: figma.enum('Status', {
                'Read-only': true,
            }),
            error: figma.enum('Status', {
                Error: figma.textContent('Error'),
            }),
        },
        example: ({indeterminate, label, disabled, readOnly, error}) => (
            <Checkbox
                indeterminate={indeterminate}
                label={label}
                disabled={disabled}
                readOnly={readOnly}
                error={error}
            />
        ),
    },
);
