import {CheckboxIcon} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    CheckboxIcon,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50069',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            indeterminate: figma.enum('Checked', {
                Indeterminate: true,
            }),
            // No matching props could be found for these Figma properties:
            // "showLabel": figma.boolean('Show Label'),
            // "state": figma.enum('State', {
            //   "Default": "default",
            //   "Disabled": "disabled"
            // }),
            // "status": figma.enum('Status', {
            //   "Default": "default",
            //   "Read-only": "read-only",
            //   "Error": "error"
            // }),
            // "caption": figma.boolean('Caption')
        },
        example: (props) => <CheckboxIcon indeterminate={props.indeterminate} />,
    },
);
