import {Chip} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    Chip,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A51718',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            checked: figma.enum('State', {
                Checked: true,
            }),
            ta: figma.enum('State', {
                Checked: 'end',
            }),
            disabled: figma.enum('State', {
                Disabled: true,
            }),
        },
        example: (props) => <Chip checked={props.checked} ta={props.ta} disabled={props.disabled} />,
    },
);
