import {Chip} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    Chip,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma-3.0---Components?node-id=7-51718&m=dev',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            checked: figma.enum('State', {
                Checked: true,
            }),
            disabled: figma.enum('State', {
                Disabled: true,
            }),
            children: figma.string('Children'),
        },
        example: ({checked, disabled, children}) => (
            <Chip checked={checked} disabled={disabled}>
                {children}
            </Chip>
        ),
    },
);
