import {CodeEditor} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    CodeEditor,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A49401',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            ta: figma.enum('State', {
                Added: 'end',
            }),
            // No matching props could be found for these Figma properties:
            // "indent1": figma.boolean('Indent 1'),
            // "indent2": figma.boolean('Indent 2'),
            // "indent3": figma.boolean('Indent 3')
        },
        example: (props) => <CodeEditor ta={props.ta} />,
    },
);
