import {CopyToClipboard} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    CopyToClipboard,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A52264',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            disabled: figma.enum('Variant', {
                Disabled: true,
            }),
            variant: figma.enum('Variant', {
                Disabled: 'subtle',
                Default: 'default',
            }),
        },
        example: (props) => <CopyToClipboard value="" disabled={props.disabled} variant={props.variant} />,
    },
);
