import {DateRangePickerInlineCalendar} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    DateRangePickerInlineCalendar,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A48121',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "showTimeInput": figma.boolean('Show Time Input'),
            // "showBottomButtons": figma.boolean('Show bottom buttons'),
            // "level": figma.enum('Level', {
            //   "Month": "month",
            //   "Year": "year",
            //   "Decade": "decade",
            //   "Time": "time"
            // })
        },
        example: (props) => (
            <DateRangePickerInlineCalendar initialRange={/* TODO */} onApply={/* TODO */} onCancel={/* TODO */} />
        ),
    },
);
