import {Header} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    Header,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A51764',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "property": figma.enum('Property', {
            //   "Default": "default",
            //   "Tabs": "tabs",
            //   "Search Bar": "search-bar",
            //   "Filter Rules": "filter-rules",
            //   "Detail Card": "detail-card",
            //   "List page": "list-page",
            //   "Create/edit": "create-edit"
            // })
        },
        example: (props) => <Header />,
    },
);
