import {HeaderBreadcrumbs} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    HeaderBreadcrumbs,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A49714',
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "items": figma.enum('Items', {
            //   "1": "1",
            //   "2": "2",
            //   "3": "3",
            //   "4": "4",
            //   "5": "5"
            // })
        },
        example: (props) => <HeaderBreadcrumbs />,
    },
);
