import {Modal} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    Modal,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50772',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            size: figma.enum('Size', {
                xSmall: 'xs',
                Small: 'sm',
                xLarge: 'xl',
            }),
            // No matching props could be found for these Figma properties:
            // "swapPlaceholder": figma.instance('Swap placeholder')
        },
        example: (props) => <Modal opened={true} onClose={() => undefined} size={props.size} />,
    },
);
