import {NavLink} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    NavLink,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma-3.0---Components?node-id=7-49985&m=dev',
    {
        props: {
            label: figma.string('Placeholder'),
            disabled: figma.enum('State', {
                Disabled: true,
            }),
            rightSection: figma.boolean('Right Icon', {
                true: figma.instance('Swap Right'),
            }),
            leftSection: figma.boolean('Left Icon', {
                true: figma.instance('Swap Left'),
            }),
            active: figma.enum('State', {
                Active: true,
            }),
        },
        example: ({label, disabled, rightSection, leftSection, active}) => (
            <NavLink
                label={label}
                disabled={disabled}
                rightSection={rightSection}
                leftSection={leftSection}
                active={active}
            />
        ),
    },
);
