import {PasswordInput} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    PasswordInput,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50474',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            ta: figma.enum('State', {
                Enabled: 'end',
            }),
            disabled: figma.enum('State', {
                Disabled: true,
            }),
            placeholder: figma.string('Placeholder'),
            readOnly: figma.enum('State', {
                'Read-only': true,
            }),
            // No matching props could be found for these Figma properties:
            // "leftIcon": figma.boolean('Left Icon'),
            // "rightIcon": figma.boolean('Right Icon'),
            // "showControls": figma.boolean('Show Controls'),
            // "placeholder": figma.string('Placeholder'),
            // "showPlaceholder": figma.boolean('Show Placeholder'),
            // "swapLeft": figma.instance('Swap Left'),
            // "swapRight": figma.instance('Swap Right')
        },
        example: (props) => (
            <PasswordInput
                ta={props.ta}
                disabled={props.disabled}
                placeholder={props.placeholder}
                readOnly={props.readOnly}
            />
        ),
    },
);
