import {Select} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
    Select,
    'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma---Components-Library?node-id=7%3A50555',
    {
        props: {
            // These props were automatically mapped based on your linked code:
            ta: figma.enum('State', {
                Selected: 'left',
                'Read-only': 'end',
            }),
            disabled: figma.enum('State', {
                Disabled: true,
            }),
            readOnly: figma.enum('State', {
                'Read-only': true,
            }),
            // No matching props could be found for these Figma properties:
            // "mainLabel": figma.boolean('Main Label'),
            // "showCaptionError": figma.boolean('Show Caption Error')
        },
        example: (props) => <Select ta={props.ta} disabled={props.disabled} readOnly={props.readOnly} />,
    },
);
