import {Slider} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Slider, 'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma-3.0---Components?node-id=7-51247', {
    props: {
        // These props were automatically mapped based on your linked code:
        disabled: figma.enum('State', {
            Disabled: true,
        }),
        mark1: figma.boolean('Mark 1', {true: 0}),
        mark2: figma.boolean('Mark 2', {true: 0}),
        mark3: figma.boolean('Mark 3', {true: 0}),
        mark4: figma.boolean('Mark 4', {true: 0}),
        mark5: figma.boolean('Mark 5', {true: 0}),
        mark6: figma.boolean('Mark 6', {true: 0}),
        mark7: figma.boolean('Mark 7', {true: 0}),
    },
    example: (props) => <Slider disabled={props.disabled} marks={[{value: props.mark1, label: props.mark1}]} />,
});
