import {Slider} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Slider, 'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma-3.0---Components?node-id=7-51247', {
    props: {
        // These props were automatically mapped based on your linked code:
        disabled: figma.enum('State', {
            Disabled: true,
        }),
    },
    example: (props) => <Slider disabled={props.disabled} />,
});
