import {Switch} from '@coveord/plasma-mantine';
import {figma} from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Switch, 'https://www.figma.com/design/FIkUthFdwxiJKSBE06qjY0/Plasma-3.0---Components?node-id=2250-5136', {
    props: {
        labelProps: figma.nestedProps('Input.Label', {
            label: figma.string('Label'),
            required: figma.boolean('Asterisk'),
        }),
        descriptionProps: figma.nestedProps('Input.Description', {
            description: figma.string('Description'),
        }),
        errorProps: figma.nestedProps('Input.Error', {
            error: figma.string('Error'),
        }),
        disabled: figma.enum('State', {
            Disabled: true,
        }),
        readOnly: figma.enum('State', {
            'Read-only': true,
        }),
        checked: figma.enum('Checked', {
            True: true,
        }),
    },
    example: ({labelProps, descriptionProps, errorProps, disabled, readOnly, checked}) => (
        <Switch
            checked={checked}
            label={labelProps.label}
            description={descriptionProps.description}
            required={labelProps.required}
            disabled={disabled}
            readOnly={readOnly}
            error={errorProps.error}
        />
    ),
});
