name: Check Scan Alerts
description: Check for high alerts
runs:
    using: composite
    steps:
        - uses: actions/github-script@v6
          with:
              script: |
                  const checkScanAlerts = require('./.github/actions/check-scan-alerts/index.js');
                  await checkScanAlerts({github, context});
