export type SvgNames =
    | ''
    | 'accessPrivate'
    | 'accessSecured'
    | 'accessShared'
    | 'activate'
    | 'activity'
    | 'add'
    | 'ai16px'
    | 'arrowBottom'
    | 'arrowBottomRounded'
    | 'arrowDownInCircle'
    | 'arrowHeadBottomStrokedLarge'
    | 'arrowHeadBottomStrokedMedium'
    | 'arrowHeadBottomStrokedSmall'
    | 'arrowHeadTopStrokedLarge'
    | 'arrowHeadTopStrokedMedium'
    | 'arrowHeadTopStrokedSmall'
    | 'arrowLeft'
    | 'arrowLeftReturn'
    | 'arrowLeftRounded'
    | 'arrowRight'
    | 'arrowRightLink'
    | 'arrowRightRounded'
    | 'arrowTop'
    | 'arrowTopRounded'
    | 'arrowTopSlim'
    | 'ascDesc'
    | 'askAlex'
    | 'associate'
    | 'availability'
    | 'average'
    | 'behaviouralAnalytics16px'
    | 'behaviouralAnalytics24px'
    | 'bellStrokedMedium'
    | 'bgWave'
    | 'body'
    | 'brain'
    | 'bubble16px'
    | 'bubble32px'
    | 'cancel'
    | 'card16px'
    | 'card32px'
    | 'cardDataAddContent'
    | 'cardGraphAddContent'
    | 'cardMove'
    | 'cardTableAddContent'
    | 'cardTypeBarChartHorizontal'
    | 'cardTypeBarChartVertical'
    | 'cardTypeBubbleChart'
    | 'cardTypeDetailedStatistics'
    | 'cardTypeLineChartBar'
    | 'cardTypeLineChartLine'
    | 'cardTypeMap'
    | 'cardTypeNote'
    | 'cardTypePieChartDonut'
    | 'cardTypePieChartPie'
    | 'cardTypeQuickMetric'
    | 'cardTypeTrend'
    | 'catalogSourceSm'
    | 'chartDown'
    | 'chartNew'
    | 'chartStable'
    | 'chartUp'
    | 'check'
    | 'checkNotAllSelected'
    | 'checkStrokedLarge'
    | 'checkStrokedMedium'
    | 'checkStrokedSmall'
    | 'checkmark'
    | 'clear'
    | 'clearSmall'
    | 'clock16px'
    | 'clock24px'
    | 'close'
    | 'cloud'
    | 'cloudLightStroked16'
    | 'cloudLightStroked24'
    | 'cloudLightStroked32'
    | 'clouds'
    | 'commerce16px'
    | 'condition'
    | 'copy'
    | 'coveoIcon16px'
    | 'crawlingBot'
    | 'crawlingBotStroked16'
    | 'crawlingBotStroked24'
    | 'crawlingBotStroked32'
    | 'criticalStrokedLarge'
    | 'criticalStrokedMedium'
    | 'criticalStrokedSmall'
    | 'dashboard'
    | 'dashboardAddcard'
    | 'dashboardDuplicate'
    | 'dashboardReset'
    | 'dashboardSave'
    | 'database'
    | 'database16px'
    | 'dateToday'
    | 'delete'
    | 'details'
    | 'disable'
    | 'domainGoogle'
    | 'domainOffice365'
    | 'domainSalesforce'
    | 'domainSaml'
    | 'domainSamlGradient'
    | 'download'
    | 'dragDrop'
    | 'dropdownDate'
    | 'dropdownTime'
    | 'duplicate'
    | 'ecommerceYellow'
    | 'edit'
    | 'elastic'
    | 'email'
    | 'emailSent'
    | 'enterprise16px'
    | 'enterprise24px'
    | 'enterprise32px'
    | 'exclamationMarkInCircle'
    | 'exclamationMarkInFullCircle'
    | 'exclude'
    | 'exit'
    | 'expand'
    | 'expendTableRight'
    | 'exploreSampleDataset'
    | 'explorer'
    | 'explorerExpand'
    | 'export'
    | 'exportagain'
    | 'external'
    | 'file16px'
    | 'file24px'
    | 'file32px'
    | 'filter'
    | 'filterAdd'
    | 'filterFacet'
    | 'flagAu'
    | 'flagEu'
    | 'flagUs'
    | 'flecheStratus'
    | 'folderClose'
    | 'folderLock'
    | 'folderOpen'
    | 'ftAttachment'
    | 'ftCalendar'
    | 'ftCase'
    | 'ftCustom'
    | 'ftDocument'
    | 'ftFeaturedResult'
    | 'ftFile'
    | 'ftFolder'
    | 'ftImages'
    | 'ftKb'
    | 'ftLink'
    | 'ftList'
    | 'ftMail'
    | 'ftRankingRules'
    | 'ftSalesforceDoctypeExcel'
    | 'ftSalesforceDoctypeFlash'
    | 'ftSalesforceDoctypeGdoc'
    | 'ftSalesforceDoctypeHtml'
    | 'ftSalesforceDoctypeImage'
    | 'ftSalesforceDoctypePack'
    | 'ftSalesforceDoctypePdf'
    | 'ftSalesforceDoctypePpt'
    | 'ftSalesforceDoctypeVisio'
    | 'ftSalesforceDoctypeWord'
    | 'ftSalesforceStandardAccount'
    | 'ftSalesforceStandardArticle'
    | 'ftSalesforceStandardCampaign'
    | 'ftSalesforceStandardContact'
    | 'ftSalesforceStandardContract'
    | 'ftSalesforceStandardDashboard'
    | 'ftSalesforceStandardDefault'
    | 'ftSalesforceStandardEmail'
    | 'ftSalesforceStandardEvent'
    | 'ftSalesforceStandardFeed'
    | 'ftSalesforceStandardFeedback'
    | 'ftSalesforceStandardFile'
    | 'ftSalesforceStandardGoals'
    | 'ftSalesforceStandardGroups'
    | 'ftSalesforceStandardInsights'
    | 'ftSalesforceStandardLead'
    | 'ftSalesforceStandardNote'
    | 'ftSalesforceStandardOpportunity'
    | 'ftSalesforceStandardOrders'
    | 'ftSalesforceStandardPost'
    | 'ftSalesforceStandardProduct'
    | 'ftSalesforceStandardQuestionFeed'
    | 'ftSalesforceStandardQuotes'
    | 'ftSalesforceStandardRelatedList'
    | 'ftSalesforceStandardReport'
    | 'ftSalesforceStandardTask'
    | 'ftSalesforceStandardTeamMember'
    | 'ftSalesforceStandardTopic'
    | 'ftUser'
    | 'ftVideo'
    | 'ftWebpage'
    | 'fullview'
    | 'gear'
    | 'groupMember'
    | 'hamburger'
    | 'headset'
    | 'headset16px'
    | 'headset216px'
    | 'headset24px'
    | 'headset32px'
    | 'help'
    | 'helpNoFill'
    | 'helpNoFill18'
    | 'hide'
    | 'history'
    | 'home'
    | 'home16px'
    | 'ideaStrokedLarge'
    | 'ideaStrokedMedium'
    | 'ideaStrokedSmall'
    | 'identityGroup'
    | 'identityUser'
    | 'inAppTeaser'
    | 'index'
    | 'indexWebsite'
    | 'info'
    | 'info14'
    | 'infoReversed'
    | 'infoStrokedLarge'
    | 'infoStrokedMedium'
    | 'infoStrokedSmall'
    | 'interfaceEditor'
    | 'invert'
    | 'keyStroked16'
    | 'keyStroked24'
    | 'keyStroked32'
    | 'labelValue'
    | 'lightning'
    | 'limiSizeStorage'
    | 'limitDocument'
    | 'limitSizeData'
    | 'limitSizeFile'
    | 'limitSource'
    | 'limitUser'
    | 'link'
    | 'lock'
    | 'logo'
    | 'logoCloud'
    | 'Administration Console'
    | 'logoSymbol'
    | 'logoSymbolOriginal'
    | 'logoWhite'
    | 'logout'
    | 'logoutStrokedMedium'
    | 'logs'
    | 'maintenance'
    | 'mappingExtractionLiteral'
    | 'mappingExtractionMetadata'
    | 'mappingExtractionScript'
    | 'menu'
    | 'menuAnalytics'
    | 'menuContent'
    | 'menuInfrastructure'
    | 'menuLock'
    | 'menuOptimization'
    | 'menuOrganization'
    | 'menuPermissions'
    | 'messageAlert'
    | 'messageAuthentification'
    | 'messageError'
    | 'minus'
    | 'more'
    | 'moreAppend'
    | 'moveNewFile'
    | 'movetonewfile'
    | 'multipleChannel'
    | 'noContent'
    | 'notGroupMember'
    | 'noteNo'
    | 'noteYes'
    | 'notification'
    | 'open'
    | 'organization16px'
    | 'organization24px'
    | 'organization32px'
    | 'pause'
    | 'peak'
    | 'people'
    | 'pin'
    | 'play'
    | 'plus'
    | 'plus16px'
    | 'plus32px'
    | 'polygons'
    | 'previewError'
    | 'pricetag'
    | 'product'
    | 'push16px'
    | 'push24px'
    | 'push32px'
    | 'pushSourceSm'
    | 'questionStrokedLarge'
    | 'questionStrokedMedium'
    | 'questionStrokedSmall'
    | 'readyToReceiveContent24px'
    | 'readyToReceiveContent32px'
    | 'rectangle'
    | 'refresh'
    | 'remove'
    | 'reorder'
    | 'rocket'
    | 'salesforce'
    | 'salesforceSansNuage'
    | 'search'
    | 'search16px'
    | 'select'
    | 'sendEmail'
    | 'setToNow'
    | 'settings'
    | 'setto'
    | 'share'
    | 'shield'
    | 'singleChannel'
    | 'sitemapSourceSm'
    | 'slack'
    | 'sliderHandle'
    | 'sortAsc'
    | 'sortDesc'
    | 'sortedAsc'
    | 'sortedDesc'
    | 'sourceAha'
    | 'sourceAll'
    | 'sourceAmazonS3'
    | 'sourceBox'
    | 'sourceCatalog'
    | 'sourceClearspace'
    | 'sourceConfluence'
    | 'sourceConfluence2'
    | 'sourceConfluence2Cloud'
    | 'sourceCustom'
    | 'sourceDatabase'
    | 'sourceDesktop'
    | 'sourceDiscourse'
    | 'sourceDocumentum'
    | 'sourceDropbox'
    | 'sourceDropboxForBusiness'
    | 'sourceDrupal'
    | 'sourceDynamics'
    | 'sourceEktronCms'
    | 'sourceEvernote'
    | 'sourceExchange'
    | 'sourceFacebook'
    | 'sourceFileSystem'
    | 'sourceGenericRest'
    | 'sourceGmail'
    | 'sourceGoogleDriveDomainWide'
    | 'sourceGoogleDriveSingleUser'
    | 'sourceGoogleSites'
    | 'sourceGoogleplus'
    | 'sourceJira'
    | 'sourceJiraCloud'
    | 'sourceJive'
    | 'sourceJiveCloud'
    | 'sourceKhoros'
    | 'sourceKnowledgebase'
    | 'sourceLdap'
    | 'LDAP'
    | 'sourceLiferay'
    | 'sourceLinkedin'
    | 'sourceLithium'
    | 'sourceLitmos'
    | 'sourceMail'
    | 'sourceMicrosoftDynamics'
    | 'sourceMicrosoftactivedirectory'
    | 'sourceMicrosoftdynamics'
    | 'sourceNotes'
    | 'sourceOneDrive'
    | 'sourceOpentext'
    | 'sourceOracleKnowledge'
    | 'sourceOracleUcm'
    | 'sourceOutlook'
    | 'sourceProductalert'
    | 'sourcePush'
    | 'sourceQueue'
    | 'sourceReviewboard'
    | 'sourceRss'
    | 'sourceSalesforce'
    | 'sourceSalesforceContent'
    | 'sourceServicenow'
    | 'sourceSharepoint'
    | 'sourceSharepointLegacy'
    | 'sourceSharepointOnline'
    | 'sourceSitecore'
    | 'sourceSitemap'
    | 'sourceSymantecEnterpriseVault'
    | 'sourceTargetProcess2'
    | 'sourceTwitter'
    | 'sourceWeb'
    | 'sourceWeb2'
    | 'sourceWebscraper'
    | 'sourceWebsphereWcm'
    | 'sourceWindchill'
    | 'sourceYahoo'
    | 'sourceYammer'
    | 'sourceYoutube'
    | 'sourceZendesk'
    | 'star'
    | 'star16px'
    | 'star24px'
    | 'star32px'
    | 'status'
    | 'statusLimiteSource'
    | 'statusLimiteUser'
    | 'statusOrgBackup'
    | 'statusOrgExpiration'
    | 'statusOrgReadOnly'
    | 'statusOrgStop'
    | 'statusSearchDown'
    | 'statusTooLong'
    | 'stop'
    | 'success24px'
    | 'success32px'
    | 'table'
    | 'thumbDown'
    | 'thumbUp'
    | 'tips'
    | 'trendDown'
    | 'trendNew'
    | 'trendStable'
    | 'trendUp'
    | 'triangle'
    | 'unchecked'
    | 'unlink'
    | 'unlock'
    | 'unlockStroked16'
    | 'unlockStroked24'
    | 'unlockStroked32'
    | 'update'
    | 'updateFullRefresh'
    | 'updateIncRefresh'
    | 'updateRebuild'
    | 'upload'
    | 'userStrokedLarge'
    | 'userStrokedMedium'
    | 'variant'
    | 'variants'
    | 'view'
    | 'warningStrokedLarge'
    | 'warningStrokedMedium'
    | 'warningStrokedSmall'
    | 'web'
    | 'webSourceSm'
    | 'websiteSearchGreen'
    | 'youtubeSourceSm'
    | 'zoomNegative'
    | 'zoomPositive';

export const SVG_NAMES: Record<Exclude<SvgNames, ''>, string> = {
    accessPrivate: 'accessPrivate',
    accessSecured: 'accessSecured',
    accessShared: 'accessShared',
    activate: 'activate',
    activity: 'activity',
    add: 'add',
    ai16px: 'ai16px',
    arrowBottom: 'arrowBottom',
    arrowBottomRounded: 'arrowBottomRounded',
    arrowDownInCircle: 'arrowDownInCircle',
    arrowHeadBottomStrokedLarge: 'arrowHeadBottomStrokedLarge',
    arrowHeadBottomStrokedMedium: 'arrowHeadBottomStrokedMedium',
    arrowHeadBottomStrokedSmall: 'arrowHeadBottomStrokedSmall',
    arrowHeadTopStrokedLarge: 'arrowHeadTopStrokedLarge',
    arrowHeadTopStrokedMedium: 'arrowHeadTopStrokedMedium',
    arrowHeadTopStrokedSmall: 'arrowHeadTopStrokedSmall',
    arrowLeft: 'arrowLeft',
    arrowLeftReturn: 'arrowLeftReturn',
    arrowLeftRounded: 'arrowLeftRounded',
    arrowRight: 'arrowRight',
    arrowRightLink: 'arrowRightLink',
    arrowRightRounded: 'arrowRightRounded',
    arrowTop: 'arrowTop',
    arrowTopRounded: 'arrowTopRounded',
    arrowTopSlim: 'arrowTopSlim',
    ascDesc: 'ascDesc',
    askAlex: 'askAlex',
    associate: 'associate',
    availability: 'availability',
    average: 'average',
    behaviouralAnalytics16px: 'behaviouralAnalytics16px',
    behaviouralAnalytics24px: 'behaviouralAnalytics24px',
    bellStrokedMedium: 'bellStrokedMedium',
    bgWave: 'bgWave',
    body: 'body',
    brain: 'brain',
    bubble16px: 'bubble16px',
    bubble32px: 'bubble32px',
    cancel: 'cancel',
    card16px: 'card16px',
    card32px: 'card32px',
    cardDataAddContent: 'cardDataAddContent',
    cardGraphAddContent: 'cardGraphAddContent',
    cardMove: 'cardMove',
    cardTableAddContent: 'cardTableAddContent',
    cardTypeBarChartHorizontal: 'cardTypeBarChartHorizontal',
    cardTypeBarChartVertical: 'cardTypeBarChartVertical',
    cardTypeBubbleChart: 'cardTypeBubbleChart',
    cardTypeDetailedStatistics: 'cardTypeDetailedStatistics',
    cardTypeLineChartBar: 'cardTypeLineChartBar',
    cardTypeLineChartLine: 'cardTypeLineChartLine',
    cardTypeMap: 'cardTypeMap',
    cardTypeNote: 'cardTypeNote',
    cardTypePieChartDonut: 'cardTypePieChartDonut',
    cardTypePieChartPie: 'cardTypePieChartPie',
    cardTypeQuickMetric: 'cardTypeQuickMetric',
    cardTypeTrend: 'cardTypeTrend',
    catalogSourceSm: 'catalogSourceSm',
    chartDown: 'chartDown',
    chartNew: 'chartNew',
    chartStable: 'chartStable',
    chartUp: 'chartUp',
    check: 'check',
    checkNotAllSelected: 'checkNotAllSelected',
    checkStrokedLarge: 'checkStrokedLarge',
    checkStrokedMedium: 'checkStrokedMedium',
    checkStrokedSmall: 'checkStrokedSmall',
    checkmark: 'checkmark',
    clear: 'clear',
    clearSmall: 'clearSmall',
    clock16px: 'clock16px',
    clock24px: 'clock24px',
    close: 'close',
    cloud: 'cloud',
    cloudLightStroked16: 'cloudLightStroked16',
    cloudLightStroked24: 'cloudLightStroked24',
    cloudLightStroked32: 'cloudLightStroked32',
    clouds: 'clouds',
    commerce16px: 'commerce16px',
    condition: 'condition',
    copy: 'copy',
    coveoIcon16px: 'coveoIcon16px',
    crawlingBot: 'crawlingBot',
    crawlingBotStroked16: 'crawlingBotStroked16',
    crawlingBotStroked24: 'crawlingBotStroked24',
    crawlingBotStroked32: 'crawlingBotStroked32',
    criticalStrokedLarge: 'criticalStrokedLarge',
    criticalStrokedMedium: 'criticalStrokedMedium',
    criticalStrokedSmall: 'criticalStrokedSmall',
    dashboard: 'dashboard',
    dashboardAddcard: 'dashboardAddcard',
    dashboardDuplicate: 'dashboardDuplicate',
    dashboardReset: 'dashboardReset',
    dashboardSave: 'dashboardSave',
    database: 'database',
    database16px: 'database16px',
    dateToday: 'dateToday',
    delete: 'delete',
    details: 'details',
    disable: 'disable',
    domainGoogle: 'domainGoogle',
    domainOffice365: 'domainOffice365',
    domainSalesforce: 'domainSalesforce',
    domainSaml: 'domainSaml',
    domainSamlGradient: 'domainSamlGradient',
    download: 'download',
    dragDrop: 'dragDrop',
    dropdownDate: 'dropdownDate',
    dropdownTime: 'dropdownTime',
    duplicate: 'duplicate',
    ecommerceYellow: 'ecommerceYellow',
    edit: 'edit',
    elastic: 'elastic',
    email: 'email',
    emailSent: 'emailSent',
    enterprise16px: 'enterprise16px',
    enterprise24px: 'enterprise24px',
    enterprise32px: 'enterprise32px',
    exclamationMarkInCircle: 'exclamationMarkInCircle',
    exclamationMarkInFullCircle: 'exclamationMarkInFullCircle',
    exclude: 'exclude',
    exit: 'exit',
    expand: 'expand',
    expendTableRight: 'expendTableRight',
    exploreSampleDataset: 'exploreSampleDataset',
    explorer: 'explorer',
    explorerExpand: 'explorerExpand',
    export: 'export',
    exportagain: 'exportagain',
    external: 'external',
    file16px: 'file16px',
    file24px: 'file24px',
    file32px: 'file32px',
    filter: 'filter',
    filterAdd: 'filterAdd',
    filterFacet: 'filterFacet',
    flagAu: 'flagAu',
    flagEu: 'flagEu',
    flagUs: 'flagUs',
    flecheStratus: 'flecheStratus',
    folderClose: 'folderClose',
    folderLock: 'folderLock',
    folderOpen: 'folderOpen',
    ftAttachment: 'ftAttachment',
    ftCalendar: 'ftCalendar',
    ftCase: 'ftCase',
    ftCustom: 'ftCustom',
    ftDocument: 'ftDocument',
    ftFeaturedResult: 'ftFeaturedResult',
    ftFile: 'ftFile',
    ftFolder: 'ftFolder',
    ftImages: 'ftImages',
    ftKb: 'ftKb',
    ftLink: 'ftLink',
    ftList: 'ftList',
    ftMail: 'ftMail',
    ftRankingRules: 'ftRankingRules',
    ftSalesforceDoctypeExcel: 'ftSalesforceDoctypeExcel',
    ftSalesforceDoctypeFlash: 'ftSalesforceDoctypeFlash',
    ftSalesforceDoctypeGdoc: 'ftSalesforceDoctypeGdoc',
    ftSalesforceDoctypeHtml: 'ftSalesforceDoctypeHtml',
    ftSalesforceDoctypeImage: 'ftSalesforceDoctypeImage',
    ftSalesforceDoctypePack: 'ftSalesforceDoctypePack',
    ftSalesforceDoctypePdf: 'ftSalesforceDoctypePdf',
    ftSalesforceDoctypePpt: 'ftSalesforceDoctypePpt',
    ftSalesforceDoctypeVisio: 'ftSalesforceDoctypeVisio',
    ftSalesforceDoctypeWord: 'ftSalesforceDoctypeWord',
    ftSalesforceStandardAccount: 'ftSalesforceStandardAccount',
    ftSalesforceStandardArticle: 'ftSalesforceStandardArticle',
    ftSalesforceStandardCampaign: 'ftSalesforceStandardCampaign',
    ftSalesforceStandardContact: 'ftSalesforceStandardContact',
    ftSalesforceStandardContract: 'ftSalesforceStandardContract',
    ftSalesforceStandardDashboard: 'ftSalesforceStandardDashboard',
    ftSalesforceStandardDefault: 'ftSalesforceStandardDefault',
    ftSalesforceStandardEmail: 'ftSalesforceStandardEmail',
    ftSalesforceStandardEvent: 'ftSalesforceStandardEvent',
    ftSalesforceStandardFeed: 'ftSalesforceStandardFeed',
    ftSalesforceStandardFeedback: 'ftSalesforceStandardFeedback',
    ftSalesforceStandardFile: 'ftSalesforceStandardFile',
    ftSalesforceStandardGoals: 'ftSalesforceStandardGoals',
    ftSalesforceStandardGroups: 'ftSalesforceStandardGroups',
    ftSalesforceStandardInsights: 'ftSalesforceStandardInsights',
    ftSalesforceStandardLead: 'ftSalesforceStandardLead',
    ftSalesforceStandardNote: 'ftSalesforceStandardNote',
    ftSalesforceStandardOpportunity: 'ftSalesforceStandardOpportunity',
    ftSalesforceStandardOrders: 'ftSalesforceStandardOrders',
    ftSalesforceStandardPost: 'ftSalesforceStandardPost',
    ftSalesforceStandardProduct: 'ftSalesforceStandardProduct',
    ftSalesforceStandardQuestionFeed: 'ftSalesforceStandardQuestionFeed',
    ftSalesforceStandardQuotes: 'ftSalesforceStandardQuotes',
    ftSalesforceStandardRelatedList: 'ftSalesforceStandardRelatedList',
    ftSalesforceStandardReport: 'ftSalesforceStandardReport',
    ftSalesforceStandardTask: 'ftSalesforceStandardTask',
    ftSalesforceStandardTeamMember: 'ftSalesforceStandardTeamMember',
    ftSalesforceStandardTopic: 'ftSalesforceStandardTopic',
    ftUser: 'ftUser',
    ftVideo: 'ftVideo',
    ftWebpage: 'ftWebpage',
    fullview: 'fullview',
    gear: 'gear',
    groupMember: 'groupMember',
    hamburger: 'hamburger',
    headset: 'headset',
    headset16px: 'headset16px',
    headset216px: 'headset216px',
    headset24px: 'headset24px',
    headset32px: 'headset32px',
    help: 'help',
    helpNoFill: 'helpNoFill',
    helpNoFill18: 'helpNoFill18',
    hide: 'hide',
    history: 'history',
    home: 'home',
    home16px: 'home16px',
    ideaStrokedLarge: 'ideaStrokedLarge',
    ideaStrokedMedium: 'ideaStrokedMedium',
    ideaStrokedSmall: 'ideaStrokedSmall',
    identityGroup: 'identityGroup',
    identityUser: 'identityUser',
    inAppTeaser: 'inAppTeaser',
    index: 'index',
    indexWebsite: 'indexWebsite',
    info: 'info',
    info14: 'info14',
    infoReversed: 'infoReversed',
    infoStrokedLarge: 'infoStrokedLarge',
    infoStrokedMedium: 'infoStrokedMedium',
    infoStrokedSmall: 'infoStrokedSmall',
    interfaceEditor: 'interfaceEditor',
    invert: 'invert',
    keyStroked16: 'keyStroked16',
    keyStroked24: 'keyStroked24',
    keyStroked32: 'keyStroked32',
    labelValue: 'labelValue',
    lightning: 'lightning',
    limiSizeStorage: 'limiSizeStorage',
    limitDocument: 'limitDocument',
    limitSizeData: 'limitSizeData',
    limitSizeFile: 'limitSizeFile',
    limitSource: 'limitSource',
    limitUser: 'limitUser',
    link: 'link',
    lock: 'lock',
    logo: 'logo',
    logoCloud: 'logoCloud',
    'Administration Console': 'Administration Console',
    logoSymbol: 'logoSymbol',
    logoSymbolOriginal: 'logoSymbolOriginal',
    logoWhite: 'logoWhite',
    logout: 'logout',
    logoutStrokedMedium: 'logoutStrokedMedium',
    logs: 'logs',
    maintenance: 'maintenance',
    mappingExtractionLiteral: 'mappingExtractionLiteral',
    mappingExtractionMetadata: 'mappingExtractionMetadata',
    mappingExtractionScript: 'mappingExtractionScript',
    menu: 'menu',
    menuAnalytics: 'menuAnalytics',
    menuContent: 'menuContent',
    menuInfrastructure: 'menuInfrastructure',
    menuLock: 'menuLock',
    menuOptimization: 'menuOptimization',
    menuOrganization: 'menuOrganization',
    menuPermissions: 'menuPermissions',
    messageAlert: 'messageAlert',
    messageAuthentification: 'messageAuthentification',
    messageError: 'messageError',
    minus: 'minus',
    more: 'more',
    moreAppend: 'moreAppend',
    moveNewFile: 'moveNewFile',
    movetonewfile: 'movetonewfile',
    multipleChannel: 'multipleChannel',
    noContent: 'noContent',
    notGroupMember: 'notGroupMember',
    noteNo: 'noteNo',
    noteYes: 'noteYes',
    notification: 'notification',
    open: 'open',
    organization16px: 'organization16px',
    organization24px: 'organization24px',
    organization32px: 'organization32px',
    pause: 'pause',
    peak: 'peak',
    people: 'people',
    pin: 'pin',
    play: 'play',
    plus: 'plus',
    plus16px: 'plus16px',
    plus32px: 'plus32px',
    polygons: 'polygons',
    previewError: 'previewError',
    pricetag: 'pricetag',
    product: 'product',
    push16px: 'push16px',
    push24px: 'push24px',
    push32px: 'push32px',
    pushSourceSm: 'pushSourceSm',
    questionStrokedLarge: 'questionStrokedLarge',
    questionStrokedMedium: 'questionStrokedMedium',
    questionStrokedSmall: 'questionStrokedSmall',
    readyToReceiveContent24px: 'readyToReceiveContent24px',
    readyToReceiveContent32px: 'readyToReceiveContent32px',
    rectangle: 'rectangle',
    refresh: 'refresh',
    remove: 'remove',
    reorder: 'reorder',
    rocket: 'rocket',
    salesforce: 'salesforce',
    salesforceSansNuage: 'salesforceSansNuage',
    search: 'search',
    search16px: 'search16px',
    select: 'select',
    sendEmail: 'sendEmail',
    setToNow: 'setToNow',
    settings: 'settings',
    setto: 'setto',
    share: 'share',
    shield: 'shield',
    singleChannel: 'singleChannel',
    sitemapSourceSm: 'sitemapSourceSm',
    slack: 'slack',
    sliderHandle: 'sliderHandle',
    sortAsc: 'sortAsc',
    sortDesc: 'sortDesc',
    sortedAsc: 'sortedAsc',
    sortedDesc: 'sortedDesc',
    sourceAha: 'sourceAha',
    sourceAll: 'sourceAll',
    sourceAmazonS3: 'sourceAmazonS3',
    sourceBox: 'sourceBox',
    sourceCatalog: 'sourceCatalog',
    sourceClearspace: 'sourceClearspace',
    sourceConfluence: 'sourceConfluence',
    sourceConfluence2: 'sourceConfluence2',
    sourceConfluence2Cloud: 'sourceConfluence2Cloud',
    sourceCustom: 'sourceCustom',
    sourceDatabase: 'sourceDatabase',
    sourceDesktop: 'sourceDesktop',
    sourceDiscourse: 'sourceDiscourse',
    sourceDocumentum: 'sourceDocumentum',
    sourceDropbox: 'sourceDropbox',
    sourceDropboxForBusiness: 'sourceDropboxForBusiness',
    sourceDrupal: 'sourceDrupal',
    sourceDynamics: 'sourceDynamics',
    sourceEktronCms: 'sourceEktronCms',
    sourceEvernote: 'sourceEvernote',
    sourceExchange: 'sourceExchange',
    sourceFacebook: 'sourceFacebook',
    sourceFileSystem: 'sourceFileSystem',
    sourceGenericRest: 'sourceGenericRest',
    sourceGmail: 'sourceGmail',
    sourceGoogleDriveDomainWide: 'sourceGoogleDriveDomainWide',
    sourceGoogleDriveSingleUser: 'sourceGoogleDriveSingleUser',
    sourceGoogleSites: 'sourceGoogleSites',
    sourceGoogleplus: 'sourceGoogleplus',
    sourceJira: 'sourceJira',
    sourceJiraCloud: 'sourceJiraCloud',
    sourceJive: 'sourceJive',
    sourceJiveCloud: 'sourceJiveCloud',
    sourceKhoros: 'sourceKhoros',
    sourceKnowledgebase: 'sourceKnowledgebase',
    sourceLdap: 'sourceLdap',
    LDAP: 'LDAP',
    sourceLiferay: 'sourceLiferay',
    sourceLinkedin: 'sourceLinkedin',
    sourceLithium: 'sourceLithium',
    sourceLitmos: 'sourceLitmos',
    sourceMail: 'sourceMail',
    sourceMicrosoftDynamics: 'sourceMicrosoftDynamics',
    sourceMicrosoftactivedirectory: 'sourceMicrosoftactivedirectory',
    sourceMicrosoftdynamics: 'sourceMicrosoftdynamics',
    sourceNotes: 'sourceNotes',
    sourceOneDrive: 'sourceOneDrive',
    sourceOpentext: 'sourceOpentext',
    sourceOracleKnowledge: 'sourceOracleKnowledge',
    sourceOracleUcm: 'sourceOracleUcm',
    sourceOutlook: 'sourceOutlook',
    sourceProductalert: 'sourceProductalert',
    sourcePush: 'sourcePush',
    sourceQueue: 'sourceQueue',
    sourceReviewboard: 'sourceReviewboard',
    sourceRss: 'sourceRss',
    sourceSalesforce: 'sourceSalesforce',
    sourceSalesforceContent: 'sourceSalesforceContent',
    sourceServicenow: 'sourceServicenow',
    sourceSharepoint: 'sourceSharepoint',
    sourceSharepointLegacy: 'sourceSharepointLegacy',
    sourceSharepointOnline: 'sourceSharepointOnline',
    sourceSitecore: 'sourceSitecore',
    sourceSitemap: 'sourceSitemap',
    sourceSymantecEnterpriseVault: 'sourceSymantecEnterpriseVault',
    sourceTargetProcess2: 'sourceTargetProcess2',
    sourceTwitter: 'sourceTwitter',
    sourceWeb: 'sourceWeb',
    sourceWeb2: 'sourceWeb2',
    sourceWebscraper: 'sourceWebscraper',
    sourceWebsphereWcm: 'sourceWebsphereWcm',
    sourceWindchill: 'sourceWindchill',
    sourceYahoo: 'sourceYahoo',
    sourceYammer: 'sourceYammer',
    sourceYoutube: 'sourceYoutube',
    sourceZendesk: 'sourceZendesk',
    star: 'star',
    star16px: 'star16px',
    star24px: 'star24px',
    star32px: 'star32px',
    status: 'status',
    statusLimiteSource: 'statusLimiteSource',
    statusLimiteUser: 'statusLimiteUser',
    statusOrgBackup: 'statusOrgBackup',
    statusOrgExpiration: 'statusOrgExpiration',
    statusOrgReadOnly: 'statusOrgReadOnly',
    statusOrgStop: 'statusOrgStop',
    statusSearchDown: 'statusSearchDown',
    statusTooLong: 'statusTooLong',
    stop: 'stop',
    success24px: 'success24px',
    success32px: 'success32px',
    table: 'table',
    thumbDown: 'thumbDown',
    thumbUp: 'thumbUp',
    tips: 'tips',
    trendDown: 'trendDown',
    trendNew: 'trendNew',
    trendStable: 'trendStable',
    trendUp: 'trendUp',
    triangle: 'triangle',
    unchecked: 'unchecked',
    unlink: 'unlink',
    unlock: 'unlock',
    unlockStroked16: 'unlockStroked16',
    unlockStroked24: 'unlockStroked24',
    unlockStroked32: 'unlockStroked32',
    update: 'update',
    updateFullRefresh: 'updateFullRefresh',
    updateIncRefresh: 'updateIncRefresh',
    updateRebuild: 'updateRebuild',
    upload: 'upload',
    userStrokedLarge: 'userStrokedLarge',
    userStrokedMedium: 'userStrokedMedium',
    variant: 'variant',
    variants: 'variants',
    view: 'view',
    warningStrokedLarge: 'warningStrokedLarge',
    warningStrokedMedium: 'warningStrokedMedium',
    warningStrokedSmall: 'warningStrokedSmall',
    web: 'web',
    webSourceSm: 'webSourceSm',
    websiteSearchGreen: 'websiteSearchGreen',
    youtubeSourceSm: 'youtubeSourceSm',
    zoomNegative: 'zoomNegative',
    zoomPositive: 'zoomPositive',
};
