name: CD

on: workflow_dispatch

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: true

env:
    TURBO_TOKEN: '${{ secrets.TURBO_TOKEN }}'

permissions:
    pull-requests: write
    id-token: write
    actions: read
    contents: write
    security-events: write
    statuses: write

jobs:
    cd:
        name: Continuous Delivery
        if: github.ref_name == 'master' || github.ref_name == 'next'
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
              with:
                  egress-policy: audit

            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  fetch-depth: 0
            - name: Setup
              uses: ./.github/actions/setup
            - name: Lint
              uses: ./.github/actions/lint
              with:
                  WORKFLOW: 'cd'
            - name: Build
              uses: ./.github/actions/build
            - name: Test
              uses: ./.github/actions/test
            - name: Publish
              uses: ./.github/actions/publish
              env:
                  DEBUG: '*'
                  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
            - name: Deploy
              uses: ./.github/actions/deploy
              # Demo for next branch is deployed by the CI workflow
              if: github.ref != 'refs/heads/next'
              with:
                  AWS_ROLE: ${{ secrets.AWS_ROLE }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
            - name: Deploy Storybook to Chromatic
              env:
                  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
              run: pnpm --filter storybook run chromatic --storybookBuildDir storybook-static --ci --exit-zero-on-changes --auto-accept-changes --branchName=${{ github.ref_name }}
