name: Clean Demo
on:
    pull_request:
        types: [closed]
jobs:
    clean-demo:
        name: Clean PR demo
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
              with:
                  egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: ./.github/actions/cleanup-demo
              with:
                  AWS_ROLE: ${{ secrets.AWS_ROLE }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
