name: Clean Demo
on:
    pull_request:
        types: [closed]
permissions:
    contents: read

jobs:
    clean-demo:
        name: Clean PR demo
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
              with:
                  egress-policy: audit

            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
            - uses: ./.github/actions/cleanup-demo
              with:
                  AWS_ROLE: ${{ secrets.AWS_ROLE }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
