name: Patate

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    dry-publish:
        name: Dry publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
              with:
                  fetch-depth: 0
            - uses: ./.github/actions/setup
            - name: Deploy
              uses: ./.github/actions/deploy
              # Demo for next branch is deployed by the CI workflow
              if: github.ref != 'refs/heads/next'
              with:
                  AWS_ROLE: ${{ secrets.AWS_ROLE }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

