name: Publish Figma Components
on:
    push:
        paths:
            - '**/*.figma.tsx'
        branches:
            - master

permissions:
  contents: read

jobs:
    code-connect-publish:
        name: Code Connect Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
            - uses: ./.github/actions/setup
            - name: Harden Runner
              uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
              with:
                  egress-policy: audit
            - name: Publish changes to Figma
              run: pnpm figma:publish
              working-directory: packages/figma
              env:
                  FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_TOKEN }}
