name: Release PR

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

jobs:
    release-pr:
        name: Create Or Update Release PR
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
              with:
                  egress-policy: audit

            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  fetch-depth: 0
            - uses: ./.github/actions/setup
            - name: Create or update the Changesets release PR
              uses: changesets/action@v1
              with:
                  commit: 'chore(release): version packages'
                  title: 'chore(release): version packages'
                  version: pnpm changeset:version
                  commitMode: github-api
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
